### PR TITLE
fix(gitalk): 422 valid failed (#132)

### PR DESCRIPTION
**Pull request by Wizardgreen**
Fix issue #132

### CODE REVIEW

**Comment by ChrAlpha** [comment]
Using the same id in theme config as gitalk id for all pages will cause all pages to have the same comments and making it impossible to distinguish comments for different pages.

Setting gitalk id at `front-matter` of each page may be a better way.

**Comment by ChrAlpha** [comment]
> Using the same id in theme config as gitalk id for all pages will cause all pages to have the same comments and making it impossible to distinguish comments for different pages.
> 
> Setting gitalk id at `front-matter` of each page may be a better way.

Please test the new commit at your convenience

**Comment by ChrAlpha** [comment]
> thx for correct my code, but now am wondering how to generate id automatically when create a new post.

Modifying the scaffolds might help with this.

However, since this is a feature of Hexo and not specific to any theme, I wouldn't mention it in theme cards.

**Comment by Wizardgreen** [comment]
> > thx for correct my code, but now am wondering how to generate id automatically when create a new post.
> 
> Modifying the scaffolds might help with this.
> 
> However, since this is a feature of Hexo and not specific to any theme, I wouldn't mention it in theme cards.

understood and new commit is good for me.

**Pull request merged**
